services:
  notebooks_cuda:
    build: ./cuda
    depends_on: 
      - postgres
    container_name: notebooks_cuda
    environment:

      CUDA_LAUNCH_BLOCKING: 1
    network_mode: host
    volumes:
      - ../notebooks:/home/jovyan/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, utility, compute]

  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: